// Auth
export const SET_USER = "SET_USER";
export const AUTH_ERROR = "AUTH_ERROR";

// Accounts
export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const ACCOUNTS_IN_PROCESS = "ACCOUNTS_IN_PROCESS";
export const ACCOUNTS_ERROR = "ACCOUNTS_ERROR";

// Labels
export const GET_LABELS = "GET_LABELS";
export const LABELS_IN_PROCESS = "LABELS_IN_PROCESS";
export const LABELS_ERROR = "LABELS_ERROR";

// Input
export const GET_FILES = "GET_FILES";
export const FILES_ERROR = "FILES_ERROR";
export const GET_SHEETS = "GET_SHEETS";
export const SHEET_ERROR = "SHEET_ERROR";
export const UPDATE_SHEETS = "UPDATE_SHEETS";

// Display
export const ADD_INFO = "ADD_INFO";
export const UPDATE_INFO = "UPDATE_INFO";
export const CHANGE_PROGRESS = "CHANGE_PROGRESS";
export const TOGGLE_PROGRESS = "TOGGLE_PROGRESS";

// Connect
export const CONNECT_SHEET_DATA = "CONNECT_SHEET_DATA";
export const CONNECT_GET_LABELS = "CONNECT_GET_LABELS";
export const CONNECT_GET_GMAIL_THREADS = "CONNECT_GET_GMAIL_THREADS";
export const CONNECT_GET_DB_THREADS = "CONNECT_GET_DB_THREADS";
export const CONNECT_NEED_TO_CREATE = "CONNECT_NEED_TO_CREATE";
export const CONNECT_NEED_TO_UPDATE = "CONNECT_NEED_TO_UPDATE";
export const CONNECT_NEED_TO_DELETE = "CONNECT_NEED_TO_DELETE";
export const CONNECT_GET_LABEL_MAP = "CONNECT_GET_LABEL_MAP";
export const CONNECT_GET_COMPRED = "CONNECT_GET_COMPRED";
export const CONNECT_UPDATE = "CONNECT_UPDATE";
